server:
  port: 8090

baseUrl: http://localhost:9595/bank/accounts/getAccountDetailsByNumber/8119008115

spring:
  application:
    name: app

tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

